sudo: false

git:
  depth: 10

branches:
  only:
    - master

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: '12'
      script: npm run pretest
    - node_js: '12'
      script: npm run test
    - node_js: '10'
      script: npm run test
    - node_js: '8'
      script: npm run test

before_install:
  - npm install -g npm@latest
  - node --version
  - npm --version
